export const DAYTYPE = 11
export const COINTYPE = 12;
export const RELATION = 15;
export const MONTH = 4;
export const MODEOFTRANSACTION = 14;
export const DAYURL = 'day/';
export const EXPENSEURL = 'expense/';
export const COMMONURL = 'common/';
// export const AUTHENTICATIONURL = 'authentication/';
export const LOGINURL = 'login/';
export const USERURL = 'user/';
export const ASSETURL = 'asset/';
export const CURRENCYCOINURL = 'CollectionCoin/';
export const ATTACHMENT = "../../assets/ProjectAttatchments/"; // Should be compared with "PhysicalPathDirectory" in "AppSettings" in DotNet
export const COLLECTIONCOINS = "Collection_Coins";
export const BIRTHDAYPERSONPIC = "Birthday_Person_Pic";